### ISSUE TITLE
Error in Runbot Docker

### ISSUE THREAD

**Issue by parthivgls** [it-projects-llc/odoo-runbot-docker#14]
Following your steps mentioned in the README.md ends up with following traceback.

```
2017-11-19 06:12:17,904 236 ERROR runbot openerp.service.server: Worker (236) Exception occured, exiting...
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 757, in run
    self.start()
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 802, in start
    self.server = BaseWSGIServerNoBind(self.multi.app)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 69, in __init__
    werkzeug.serving.BaseWSGIServer.__init__(self, "1", "1", app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 506, in __init__
    self.port = self.socket.getsockname()[1]
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

```

**Comment by oliverzgy** [comment]
@parthivgls Hi Parthiv how did you fix this issue? Thanks

**Comment by YogeshMahera-SerpentCS** [comment]
Hi @parthivgls How do you resolve this issue?
