### ISSUE TITLE
Unable

### ISSUE THREAD

**Issue by online-sanaullah** [it-projects-llc/odoo-runbot-docker#15]
Hi,

Whenever I create a runbot container I get the following error in the logs and the service in the container fails to start

> docker run -h runbot.smartway-jo.com -p 18069:8069 -p 8080:8080 -v /home/smartway/services/odoo/data:/var/lib/odoo --link db-9.5:db --link postfix:postfix --name odoo-runbot -t itprojectsllc/odoo-runbot-docker
> 2018-03-21 10:07:23,873 1 INFO ? openerp: OpenERP version 8.0-20170207
> 2018-03-21 10:07:23,874 1 INFO ? openerp: addons paths: [u'/mnt/odoo-extra', u'/mnt/extra-addons', u'/mnt/runbot-addons', u'/usr/lib/python2.7/dist-packages/openerp/addons']
> 2018-03-21 10:07:23,874 1 INFO ? openerp: database hostname: 172.17.0.3
> 2018-03-21 10:07:23,874 1 INFO ? openerp: database port: 5432
> 2018-03-21 10:07:23,874 1 INFO ? openerp: database user: odoo
> 2018-03-21 10:07:24,078 1 INFO runbot openerp.modules.loading: loading 1 modules...
> 2018-03-21 10:07:24,086 1 INFO runbot openerp.modules.loading: 1 modules loaded in 0.01s, 0 queries
> 2018-03-21 10:07:24,230 1 INFO runbot openerp.modules.loading: Modules loaded.
> 2018-03-21 10:07:24,231 1 INFO runbot openerp.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections 
> 2018-03-21 10:07:24,232 12 INFO runbot openerp.service.server: Worker WorkerHTTP (12) alive
> 2018-03-21 10:07:24,233 13 INFO runbot openerp.service.server: Worker WorkerHTTP (13) alive
> 2018-03-21 10:07:24,234 12 ERROR runbot openerp.service.server: Worker (12) Exception occured, exiting...
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 757, in run
>     self.start()
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 802, in start
>     self.server = BaseWSGIServerNoBind(self.multi.app)
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 69, in __init__
>     werkzeug.serving.BaseWSGIServer.__init__(self, "1", "1", app)
>   File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 506, in __init__
>     self.port = self.socket.getsockname()[1]
>   File "/usr/lib/python2.7/socket.py", line 224, in meth
>     return getattr(self._sock,name)(*args)
>   File "/usr/lib/python2.7/socket.py", line 170, in _dummy
>     raise error(EBADF, 'Bad file descriptor')
> error: [Errno 9] Bad file descriptor
> 2018-03-21 10:07:24,235 13 ERROR runbot openerp.service.server: Worker (13) Exception occured, exiting...
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 757, in run
>     self.start()
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 802, in start
>     self.server = BaseWSGIServerNoBind(self.multi.app)
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 69, in __init__
>     werkzeug.serving.BaseWSGIServer.__init__(self, "1", "1", app)
>   File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 506, in __init__
>     self.port = self.socket.getsockname()[1]
>   File "/usr/lib/python2.7/socket.py", line 224, in meth
>     return getattr(self._sock,name)(*args)
>   File "/usr/lib/python2.7/socket.py", line 170, in _dummy
>     raise error(EBADF, 'Bad file descriptor')
> error: [Errno 9] Bad file descriptor
> 2018-03-21 10:07:24,257 15 INFO runbot openerp.service.server: Worker WorkerCron (15) alive
> 2018-03-21 10:07:24,269 16 INFO runbot openerp.service.server: Worker WorkerCron (16) alive
> 2018-03-21 10:07:24,303 17 INFO runbot openerp.service.server: Worker WorkerHTTP (17) alive
> 2018-03-21 10:07:24,303 18 INFO runbot openerp.service.server: Worker WorkerHTTP (18) alive
> 2018-03-21 10:07:24,304 17 ERROR runbot openerp.service.server: Worker (17) Exception occured, exiting...
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 757, in run
>     self.start()
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 802, in start
>     self.server = BaseWSGIServerNoBind(self.multi.app)
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 69, in __init__
>     werkzeug.serving.BaseWSGIServer.__init__(self, "1", "1", app)
>   File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 506, in __init__
>     self.port = self.socket.getsockname()[1]
>   File "/usr/lib/python2.7/socket.py", line 224, in meth
>     return getattr(self._sock,name)(*args)
>   File "/usr/lib/python2.7/socket.py", line 170, in _dummy
>     raise error(EBADF, 'Bad file descriptor')
> error: [Errno 9] Bad file descriptor
> 2018-03-21 10:07:24,305 18 ERROR runbot openerp.service.server: Worker (18) Exception occured, exiting...
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 757, in run
>     self.start()
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 802, in start
>     self.server = BaseWSGIServerNoBind(self.multi.app)
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 69, in __init__
>     werkzeug.serving.BaseWSGIServer.__init__(self, "1", "1", app)
>   File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 506, in __init__
>     self.port = self.socket.getsockname()[1]
>   File "/usr/lib/python2.7/socket.py", line 224, in meth
>     return getattr(self._sock,name)(*args)
>   File "/usr/lib/python2.7/socket.py", line 170, in _dummy
>     raise error(EBADF, 'Bad file descriptor')
> error: [Errno 9] Bad file descriptor
> 2018-03-21 10:07:24,368 19 INFO runbot openerp.service.server: Worker WorkerHTTP (19) alive
> 2018-03-21 10:07:24,369 20 INFO runbot openerp.service.server: Worker WorkerHTTP (20) alive
> 2018-03-21 10:07:24,370 19 ERROR runbot openerp.service.server: Worker (19) Exception occured, exiting...
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 757, in run
>     self.start()
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 802, in start
>     self.server = BaseWSGIServerNoBind(self.multi.app)
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 69, in __init__
>     werkzeug.serving.BaseWSGIServer.__init__(self, "1", "1", app)
>   File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 506, in __init__
>     self.port = self.socket.getsockname()[1]
>   File "/usr/lib/python2.7/socket.py", line 224, in meth
>     return getattr(self._sock,name)(*args)
>   File "/usr/lib/python2.7/socket.py", line 170, in _dummy
>     raise error(EBADF, 'Bad file descriptor')
> error: [Errno 9] Bad file descriptor
> 2018-03-21 10:07:24,370 20 ERROR runbot openerp.service.server: Worker (20) Exception occured, exiting...
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 757, in run
>     self.start()
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 802, in start
>     self.server = BaseWSGIServerNoBind(self.multi.app)
>   File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 69, in __init__
>     werkzeug.serving.BaseWSGIServer.__init__(self, "1", "1", app)
>   File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 506, in __init__
>     self.port = self.socket.getsockname()[1]
>   File "/usr/lib/python2.7/socket.py", line 224, in meth
>     return getattr(self._sock,name)(*args)
>   File "/usr/lib/python2.7/socket.py", line 170, in _dummy
>     raise error(EBADF, 'Bad file descriptor')
> error: [Errno 9] Bad file descriptor

I am not sure what I am missing, or what I am doing wrong. @yelizariev  how can we fix this?

**Comment by yelizariev** [comment]
Sorry, I don't remember that problem

**Comment by mohamedhabibchallouf** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 757, in run
    self.start()
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 802, in start
    self.server = BaseWSGIServerNoBind(self.multi.app)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 69, in __init__
    werkzeug.serving.BaseWSGIServer.__init__(self, "1", "1", app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 506, in __init__
    self.port = self.socket.getsockname()[1]
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 170, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
2018-04-12 13:58:21,470 757 INFO ? openerp.service.server: Worker WorkerHTTP (757) alive
2018-04-12 13:58:21,472 757 ERROR ? openerp.service.server: Worker (757) Exception occured, exiting...
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 757, in run
    self.start()
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 802, in start
    self.server = BaseWSGIServerNoBind(self.multi.app)
  File "/usr/lib/python2.7/dist-packages/openerp/service/server.py", line 69, in __init__
    werkzeug.serving.BaseWSGIServer.__init__(self, "1", "1", app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 506, in __init__
    self.port = self.socket.getsockname()[1]
  File "/usr/lib/python2.7/socket.py", line 224^C

**Comment by online-sanaullah** [comment]
Actually i managed to resolve the issue by replacing the file "/usr/lib/python2.7/dist-packages/openerp/service/server.py" with the one from odoo's repository, and the service started working.

Looks like the image includes a modified file.

**Comment by mohamedhabibchallouf** [comment]
Could you give me more détails plz @online-sanaullah

**Comment by yelizariev** [comment]
I can rebuild the image, so ``server.py`` will be up-to-date

**Comment by yelizariev** [comment]
It's done. The build has latest version of odoo 8.0
Don't forget to make ``docker pull ...``

**Comment by mohamedhabibchallouf** [comment]
@yelizariev  well done thanks :+1:
